### ISSUE TITLE
最安値、最高値の店名を表示する

### ISSUE THREAD

**Issue by YuzuRyo61** [Qman11010101/SO2MarketInfoBotForDiscord#16]
最安値や最高値の店名を出した方がもしかしたらいいかもしれない

**Comment by Qman11010101** [comment]
必要か？？？必要以上に情報を氾濫させてもいいことはないと思うんだよな
それにAPIの仕様上必ずしも最新情報が表示されるとも限らないし、情報があくまでも目安である以上は情報を出すとしても店の数や価格で十分だと思うんだよな

**Comment by YuzuRyo61** [comment]
そう?

**Comment by Qman11010101** [comment]
そう、ぶっちゃけると正直店舗名を表示するメリットがないんだわ
今の時点だと表示される情報が合計12個で、これ以上の追加は視覚的にもあまり良いものとは言えないと思う
APIにリアルタイム性がないのも懸念点でな…正直もっとリアタイ性あるAPIだったら店舗名表示してもよかったんだけど、流石に個人で運営してるゲームが好意でAPI提供してくれてるところにそれは酷やろ？まあAPIにリアタイ性欲しいけどな…
つーわけで、俺は店舗名表示には反対の立場を取る
納得できたらClose、意見があればコメントつけてくれ

**Comment by YuzuRyo61** [comment]
😐

**Comment by Qman11010101** [comment]
ご理解ご協力あざす
