### ISSUE TITLE
コード内の疑似エラーについて

### ISSUE THREAD

**Issue by Qman11010101** [Qman11010101/SO2MarketInfoBotForDiscord#36]
Alias.pyにあるような、「True」「False」「None」以外の理由で止めたいときに私が仕方なく文字列を返してるの、スマートじゃなさそうなので何かしら将来的には改善したいと思ったりしている。ユーザー定義エラーとか使えるのかな

**Comment by YuzuRyo61** [comment]
raiseとか使えばできる、もちろんユーザー定義のExceptionも作れる
