### ISSUE TITLE
Herokuで動かしたときに登録されたaliasがリセットされる

### ISSUE THREAD

**Issue by Qman11010101** [Qman11010101/SO2MarketInfoBotForDiscord#37]
Heroku、一日一回再起動して状態リセットされるのきついな…家の鯖からgit pull→git add .→git commit -m "?????"→git push heroku masterとかするしかないか？？

**Comment by Qman11010101** [comment]
どっか外部にalias.json置くとかできるだろうか…

**Comment by YuzuRyo61** [comment]
Herokuの仕様上、再起動かけるとリセットがかかるみたい....

**Comment by Qman11010101** [comment]
Herokuの仕様によるものなのでどうしようもない、一旦wontfixで閉じとく
