### ISSUE TITLE
やっぱシャットダウンコマンド欲しい

### ISSUE THREAD

**Issue by Qman11010101** [Qman11010101/SO2MarketInfoBotForDiscord#39]
停止までに時間が掛かるの死ぬほどめんどくさい
コンフィグでenable/disable指定できるようにして、管理者IDも(複数人まで)なんとか指定できるようにして…ってできないかね

**Comment by YuzuRyo61** [comment]
必要かどうかって言われたらうちは否
止めるのに時間かかるのは多分ライブラリの影響だとは思うけどなぁ...最善策がそれとは限らない気がする...

**Comment by Qman11010101** [comment]
うーん、開発効率は絶対sys.exit()あったほうが上がるしこっちとしては細かい部分でイライラしながら開発するのあんまり良くないと思うんだよな
