### ISSUE TITLE
エイリアスの挙動修正

### ISSUE THREAD

**Issue by YuzuRyo61** [Qman11010101/SO2MarketInfoBotForDiscord#4]
https://github.com/Qman11010101/SO2MarketInfoBotForDiscord/blob/master/SO2MI/Alias.py

https://github.com/Qman11010101/SO2MarketInfoBotForDiscord/commit/75416c0e0c71c9052428e3a2b8d68320428e6afa#r33895046

if文の文法が悪いっぽい気がする。一回撤去してるからバグ修正を頼む

**Comment by YuzuRyo61** [comment]
これが原因だとわからずにパース処理のデバッグに時間かけてしまったのは言うまでもない・・・

**Comment by Qman11010101** [comment]
すまん…すまん…
てかifにelif積み重ねて行くのじゃだめなのか:thinking:

**Comment by Qman11010101** [comment]
てか今現在このコードでバグる？

**Comment by YuzuRyo61** [comment]
修正したら直ったが、それに気づくまでに1時間近く浪費した( ˇωˇ )

**Comment by Qman11010101** [comment]
そいつはすまなかった…
修正したのが正しく動くかチェックを求める
