### ISSUE TITLE
aliasコマンドのヘルプについて

### ISSUE THREAD

**Issue by Qman11010101** [Qman11010101/SO2MarketInfoBotForDiscord#43]
コード中にHelpの文章がいくつもあるの良くない、addとremove専用の説明はともかく、```!alias```と```!alias help```で出てくる文字列を分ける必要は無い気がするのよね
```showHelpMarket()```みたく関数化できない？

**Comment by YuzuRyo61** [comment]
🤔

**Comment by Qman11010101** [comment]
できない？？？
