### ISSUE TITLE
各pyファイルについての説明求む+α

### ISSUE THREAD

**Issue by Qman11010101** [Qman11010101/SO2MarketInfoBotForDiscord#5]
いまのところどのファイルを最初に起動してどう動くのかが見えてないので、説明を求めます…
「最初にxxx.pyを起動したらyyy.pyを読み込んでここでログインされて…」みたいな説明が欲しい…
あとjsonファイルに対してdatetime使ってるのなんでですか(現時点で過去のJsonを残す予定は無いです)

**Comment by YuzuRyo61** [comment]
README.mdは更新した

**Comment by YuzuRyo61** [comment]
> あとjsonファイルに対してdatetime使ってるのなんでですか(現時点で過去のJsonを残す予定は無いです)

仕様変更した
