### ISSUE TITLE
バージョン定義のファイルを用意する

### ISSUE THREAD

**Issue by YuzuRyo61** [Qman11010101/SO2MarketInfoBotForDiscord#53]
バージョンコマンドに直接書くのではなく、別ファイルにバージョン定義のファイルを用意してそこにバージョンを書くって感じ

**Comment by Qman11010101** [comment]
バージョン定義のファイル、具体的にどんな感じになるの？

**Comment by YuzuRyo61** [comment]
> バージョン定義のファイル、具体的にどんな感じになるの？

.version.txtとかをメインスクリプトがあるところに置いてそこにバージョンを書く
それで、そのバージョンをwithで読み出して使うところに代入する
１ファイル書き換えておけば他もそれになるから変更が楽なのではないかと

**Comment by Qman11010101** [comment]
他というか現状!versionでしか使ってないのがなあ、ただ拡張性は上がりそうだしそのほうが良さそう

**Comment by Qman11010101** [comment]
PR出してくれると助かるが…

**Comment by Qman11010101** [comment]
実際どんな形式になるん？

**Comment by Qman11010101** [comment]
PR出してほしい、あんまりイメージが掴めない

**Comment by Qman11010101** [comment]
バージョン書いてる場所が増えたので優先度高めにする

**Comment by Qman11010101** [comment]
バージョン定義ファイルを用意すべきだろうか、configでもいいような気もしないでもないがユーザー側から変更できるっぽいのもあまり望ましくないし…
いっそコード中に定数として出せばいいのではという気持ちにもなる

**Comment by YuzuRyo61** [comment]
> バージョン定義ファイルを用意すべきだろうか、configでもいいような気もしないでもないがユーザー側から変更できるっぽいのもあまり望ましくないし…
> いっそコード中に定数として出せばいいのではという気持ちにもなる

Pythonって定数の概念ないんだよな・・・（確か）

**Comment by Qman11010101** [comment]
定数の概念はまあなくても変数を定数として扱うことは可能なので…

**Comment by Qman11010101** [comment]
慣習的に変数を大文字で記述して定数とするみたいなことを言ってるサイトがあった

**Comment by YuzuRyo61** [comment]
> 定数の概念はまあなくても変数を定数として扱うことは可能なので…

関数で呼び出すってのはどうだろうか

```python
def getVersion():
  return "2.6"
```

```python
import getVersion

print(getVersion())
```

・・・的な（ファイル構造あってるかどうかは別として）

**Comment by Qman11010101** [comment]
うーん、それのためにわざわざ関数定義するのも気が引けるというか、もう少しなにかいい方法があればいいんだけど

**Comment by Qman11010101** [comment]
とりあえず、
- 定数としてバージョン定義
- 別ファイルにバージョン定義
- 関数としてバージョン定義
の3つの方法があることは理解したので、ここではとりあえず別ファイル方式を考えよう
書式はconfigみたく```version = 3.0```みたいな感じでいいのかね

**Comment by Qman11010101** [comment]
Client.py内に含めた
